# @ job_name = run_conftest
# @ comment = "run_conftest"
# @ error = $(job_name).$(jobid).out
# @ output = $(job_name).$(jobid).out
# @ environment = COPY_ALL
# @ wall_clock_limit = 00:10:00
# @ notification = never
# @ notify_user = your@name.de
# @ job_type = bluegene
# @ bg_size = 32
# @ queue


# use --np TO SPECIFY THE TOTAL NUMBER OF PROCESSORS
runjob --np 1 --ranks-per-node 1 --exe conftest-PETSC_IBM_BGP_XL_OPT