clean:
	@echo "............................................."
	@echo ".......... Performing full clean ............"
	@echo "............................................."
	@rm -f  **/*.xml
	@rm -f  **/*.pvd
	@rm -f  **/*.out
	@rm -f  **/*.log
	@rm -f  **/*.png
	@rm -f  **/*.vts
	@rm -f  **/*.bin
	@rm -rf **/*Timestep*
	@rm -rf **/*markers*
	@rm -rf **/*restart

